language: cpp
compiler: g++

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-4.9
- sudo apt-get install libopencv-dev
- sudo apt-get install libeigen3-dev
- sudo apt-get install libtbb-dev
- sudo apt-get install cmake
- export CXX="g++-4.9"

script: "bash -c ./.travis_build.sh"

